apiVersion: v1
kind: Pod
metadata:
  name: kubescan-agent
spec:
  containers:
    - name: kubescan-agent
      image: nonstandardlogic/kubescan-agent
      env:
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
  restartPolicy: Never